Repository PKU-Alignment/omnisafe, pull requests merged in 2023-03, with the labels that each got.

#119 fix(off-policy): fix action passing
  omnisafe/algorithms/off_policy/crpo.py
  omnisafe/algorithms/off_policy/ddpg.py
  omnisafe/algorithms/off_policy/ddpg_pid.py
  omnisafe/algorithms/off_policy/sac.py
  omnisafe/algorithms/off_policy/sac_lag.py
  omnisafe/algorithms/off_policy/sac_pid.py
  omnisafe/algorithms/off_policy/sddpg.py
  omnisafe/algorithms/off_policy/td3.py
  omnisafe/algorithms/off_policy/td3_lag.py
  omnisafe/algorithms/off_policy/td3_pid.py
  omnisafe/configs/off-policy/DDPG.yaml
  omnisafe/configs/off-policy/DDPGLag.yaml
  omnisafe/configs/off-policy/DDPGPid.yaml
  omnisafe/configs/off-policy/SAC.yaml
  omnisafe/configs/off-policy/SACLag.yaml
  omnisafe/configs/off-policy/TD3.yaml
  omnisafe/configs/off-policy/TD3Lag.yaml
  omnisafe/configs/off-policy/TD3Pid.yaml
  omnisafe/wrappers/cmdp_wrapper.py
Labels: bug

#174 fix(config.py): fix config assertion
  omnisafe/utils/config.py
Labels: bug, enhancement, codestyle

#172 chore: fix typo in readme
  README.md
Labels: documentation

#176 refactor(wrapper): refactor the cuda setting
  omnisafe/adapter/offpolicy_adapter.py
  omnisafe/adapter/online_adapter.py
  omnisafe/adapter/saute_adapter.py
  omnisafe/algorithms/on_policy/second_order/cpo.py
  omnisafe/algorithms/on_policy/second_order/pcpo.py
  omnisafe/envs/core.py
  omnisafe/envs/safety_gymnasium_env.py
  omnisafe/envs/wrapper.py
  omnisafe/evaluator.py
Labels: bug, enhancement, feature

#138 docs: update README and the usage of CLI
  README.md
  images/CLI_example.svg
  omnisafe/version.py
  requirements.txt
Labels: documentation

#187 docs: update changelog.md
  CHANGELOG.md
Labels: documentation

#192 feat: update CLI for gpu and statistics tools
  examples/benchmarks/run_experiment_grid.py
  omnisafe/common/experiment_grid.py
  omnisafe/common/statistics_tools.py
  omnisafe/utils/command_app.py
  tests/saved_source/benchmark_config.yaml
  tests/saved_source/train_config.yaml
  tests/test_cli.py
Labels: enhancement

#194 fix(experiment grid): fix file path problem when using gpu in experiment grid
  omnisafe/common/experiment_grid.py
  omnisafe/common/statistics_tools.py
Labels: bug, codestyle
