Repository PKU-Alignment/omnisafe, pull requests merged in 2023-05, with the labels that each got.

#227 docs: update contributing.md
  CONTRIBUTING.md
Labels: documentation, enhancement, question

#214 chore: clean some trivial code
  examples/analyze_experiment_results.py
  examples/benchmarks/run_experiment_grid.py
  examples/plot.py
  examples/train_from_custom_dict.py
  examples/train_from_yaml.py
  omnisafe/common/experiment_grid.py
  omnisafe/common/statistics_tools.py
  omnisafe/utils/command_app.py
  omnisafe/utils/exp_grid_tools.py
  tests/test_experiment_grid.py
  tests/test_utils.py
  tutorials/English/1.Getting_Started.ipynb
  tutorials/zh-cn/1.Getting Started.ipynb
Labels: codestyle

#238 feat: improve test coverage and clear redundant code.
  omnisafe/adapter/modelbased_adapter.py
  omnisafe/algorithms/model_based/base/ensemble.py
  omnisafe/algorithms/model_based/base/loop.py
  omnisafe/algorithms/model_based/planner/arc.py
  omnisafe/algorithms/model_based/planner/cem.py
  omnisafe/common/offline/dataset.py
  omnisafe/common/statistics_tools.py
  omnisafe/envs/safety_gymnasium_modelbased.py
  omnisafe/utils/command_app.py
  omnisafe/utils/exp_grid_tools.py
  omnisafe/utils/tools.py
  tests/simple_env.py
  tests/test_ensemble.py
  tests/test_offline_data.py
  tests/test_policy.py
  tests/test_statistics_tools.py
  tests/test_utils.py
Labels: enhancement, algorithm

#239 docs: change link to PKU-Alignment
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/questions.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CODEOWNERS
  CONTRIBUTING.md
  README.md
  docs/source/conf.py
  docs/source/start/usage.rst
  omnisafe/common/logger.py
  pyproject.toml
  tutorials/English/1.Getting_Started.ipynb
  tutorials/English/2.CLI_Command.ipynb
  tutorials/README.md
  tutorials/zh-cn/1.Getting Started.ipynb
  tutorials/zh-cn/2.CLI Command.ipynb
Labels: documentation

#243 fix: fix adapter device and exp grid
  omnisafe/adapter/early_terminated_adapter.py
  omnisafe/adapter/saute_adapter.py
  omnisafe/adapter/simmer_adapter.py
  omnisafe/common/experiment_grid.py
  omnisafe/common/statistics_tools.py
  omnisafe/models/actor/perturbation_actor.py
  omnisafe/models/actor/vae_actor.py
  omnisafe/models/critic/q_critic.py
  omnisafe/models/offline/dice.py
Labels: bug, algorithm, codestyle

#242 docs: polish algorithms tutorial
  docs/source/baserl/ppo.rst
  docs/source/baserl/trpo.rst
  docs/source/baserlapi/on_policy.rst
  docs/source/common/offline_data.rst
  docs/source/common/stastics_tool.rst
  docs/source/envs/adapter.rst
  docs/source/envs/core.rst
  docs/source/foundations/lagrange.rst
  docs/source/foundations/notations.rst
  docs/source/foundations/vector.rst
  docs/source/index.rst
  docs/source/model/actor.rst
  docs/source/model/offline.rst
  docs/source/saferl/cpo.rst
  docs/source/saferl/focops.rst
  docs/source/saferl/lag.rst
  docs/source/saferl/pcpo.rst
  docs/source/spelling_wordlist.txt
  docs/source/utils/config.rst
  omnisafe/algorithms/base_algo.py
  omnisafe/algorithms/off_policy/sac.py
  omnisafe/algorithms/off_policy/td3.py
  omnisafe/algorithms/on_policy/base/natural_pg.py
  omnisafe/algorithms/on_policy/base/policy_gradient.py
  omnisafe/algorithms/on_policy/base/ppo.py
  omnisafe/algorithms/on_policy/base/trpo.py
  omnisafe/algorithms/on_policy/naive_lagrange/pdo.py
  omnisafe/algorithms/on_policy/naive_lagrange/ppo_lag.py
  omnisafe/algorithms/on_policy/naive_lagrange/rcpo.py
  omnisafe/algorithms/on_policy/naive_lagrange/trpo_lag.py
  omnisafe/algorithms/on_policy/penalty_function/ipo.py
  omnisafe/algorithms/on_policy/penalty_function/p3o.py
  omnisafe/common/buffer/onpolicy_buffer.py
  omnisafe/common/buffer/vector_onpolicy_buffer.py
  omnisafe/common/experiment_grid.py
  omnisafe/common/lagrange.py
  omnisafe/common/logger.py
  omnisafe/common/normalizer.py
  omnisafe/common/offline/__init__.py
  omnisafe/common/offline/dataset.py
  omnisafe/envs/core.py
  omnisafe/envs/safety_gymnasium_env.py
  omnisafe/models/__init__.py
  omnisafe/models/actor/actor_builder.py
  omnisafe/models/actor/gaussian_learning_actor.py
  omnisafe/models/actor/gaussian_sac_actor.py
  omnisafe/models/actor/mlp_actor.py
  omnisafe/models/actor/perturbation_actor.py
  omnisafe/models/actor/vae_actor.py
  omnisafe/models/actor_critic/actor_critic.py
  omnisafe/models/actor_critic/actor_q_critic.py
  omnisafe/models/base.py
  omnisafe/models/critic/critic_builder.py
  omnisafe/models/critic/q_critic.py
  omnisafe/models/critic/v_critic.py
  omnisafe/utils/distributed.py
  omnisafe/utils/exp_grid_tools.py
  omnisafe/utils/math.py
Labels: documentation

#246 docs: polish README, benchmarks and examples
  CHANGELOG.md
  README.md
  benchmarks/model-based/README.md
  benchmarks/off-policy/README.md
  benchmarks/offline/README.md
  benchmarks/on-policy/README.md
  examples/collect_offline_data.py
  omnisafe/configs/off-policy/DDPG.yaml
  omnisafe/configs/off-policy/DDPGLag.yaml
  omnisafe/configs/off-policy/SAC.yaml
  omnisafe/configs/off-policy/SACLag.yaml
  omnisafe/configs/off-policy/TD3.yaml
  omnisafe/configs/off-policy/TD3Lag.yaml
Labels: documentation
