Repository PKU-Alignment/omnisafe, pull requests merged in 2023-04, with the labels that each got.

#198 refactor: condense top-level benchmarks
  README.md
  benchmarks/README.md
  benchmarks/off-policy/README.md
  benchmarks/off-policy/benchmarks/Ant.png
  benchmarks/off-policy/benchmarks/HalfCheetah.png
  benchmarks/off-policy/benchmarks/Hopper.png
  benchmarks/off-policy/benchmarks/Humanoid.png
  benchmarks/off-policy/benchmarks/Swimmer.png
  benchmarks/off-policy/benchmarks/Walker2d.png
  benchmarks/on-policy/README.md
  benchmarks/on-policy/benchmarks/first_order_ant.png
  benchmarks/on-policy/benchmarks/first_order_halfcheetah.png
  benchmarks/on-policy/benchmarks/first_order_hopper.png
  benchmarks/on-policy/benchmarks/first_order_humanoid.png
  benchmarks/on-policy/benchmarks/first_order_swimmer.png
  benchmarks/on-policy/benchmarks/first_order_walker2d.png
  benchmarks/on-policy/benchmarks/second_order_ant.png
  benchmarks/on-policy/benchmarks/second_order_halfcheetah.png
  benchmarks/on-policy/benchmarks/second_order_hopper.png
  benchmarks/on-policy/benchmarks/second_order_humanoid.png
  benchmarks/on-policy/benchmarks/second_order_swimmer.png
  benchmarks/on-policy/benchmarks/second_order_walker2d.png
Labels: documentation

#203 fix: check duplicated parameters and values which are specified in experiment grid
  omnisafe/common/experiment_grid.py
Labels: bug

#208 fix: enable `smooth` param in `Costs` when plotting
  omnisafe/common/statistics_tools.py
  omnisafe/utils/plotter.py
Labels: bug

#220 fix(simmer, PID): fix simmer performance and tune parameters
  omnisafe/adapter/saute_adapter.py
  omnisafe/adapter/simmer_adapter.py
  omnisafe/algorithms/on_policy/simmer/ppo_simmer_pid.py
  omnisafe/algorithms/on_policy/simmer/trpo_simmer_pid.py
  omnisafe/common/simmer_agent.py
  omnisafe/configs/on-policy/CPPOPID.yaml
  omnisafe/configs/on-policy/PPOSimmerPID.yaml
  omnisafe/configs/on-policy/TRPOLag.yaml
  omnisafe/configs/on-policy/TRPOPID.yaml
  omnisafe/configs/on-policy/TRPOSaute.yaml
  omnisafe/configs/on-policy/TRPOSimmerPID.yaml
  tests/test_policy.py
Labels: bug, algorithm, codestyle

#217 feat: add `Dockerfile` and `codecov.yml`
  .dockerignore
  .flake8
  .pre-commit-config.yaml
  Dockerfile
  Makefile
  codecov.yml
  docs/requirements.txt
  omnisafe/algorithms/registry.py
  omnisafe/utils/config.py
  requirements.txt
  setup.py
  tests/requirements.txt
Labels: enhancement, installation
