Repository PKU-Alignment/omnisafe, pull requests merged in 2023-08, with the labels that each got.

#256 feat: support new agents tasks and customizing environment guide
  README.md
  omnisafe/envs/safety_gymnasium_env.py
Labels: documentation, feature, environment

#260 feat(off-policy): fix final_obsevation setting and support evaluation times configuation
  omnisafe/adapter/offpolicy_adapter.py
  omnisafe/adapter/online_adapter.py
  omnisafe/algorithms/off_policy/ddpg.py
  omnisafe/configs/off-policy/DDPG.yaml
  omnisafe/configs/off-policy/DDPGLag.yaml
  omnisafe/configs/off-policy/DDPGPID.yaml
  omnisafe/configs/off-policy/SAC.yaml
  omnisafe/configs/off-policy/SACLag.yaml
  omnisafe/configs/off-policy/SACPID.yaml
  omnisafe/configs/off-policy/TD3.yaml
  omnisafe/configs/off-policy/TD3Lag.yaml
  omnisafe/configs/off-policy/TD3PID.yaml
Labels: bug, enhancement, algorithm

#261 style: update pre-commit.yaml and fix ruff
  .pre-commit-config.yaml
  omnisafe/algorithms/model_based/base/loop.py
  omnisafe/algorithms/model_based/base/pets.py
  omnisafe/algorithms/on_policy/second_order/pcpo.py
  omnisafe/utils/tools.py
Labels: dependency, codestyle

#266 feat: support gymnasium style reset API
  .pre-commit-config.yaml
  omnisafe/adapter/offline_adapter.py
  omnisafe/adapter/online_adapter.py
  omnisafe/adapter/saute_adapter.py
  omnisafe/adapter/simmer_adapter.py
  omnisafe/algorithms/model_based/planner/arc.py
  omnisafe/algorithms/model_based/planner/cem.py
  omnisafe/algorithms/model_based/planner/safe_arc.py
  omnisafe/common/logger.py
  omnisafe/envs/core.py
  omnisafe/envs/mujoco_env.py
  omnisafe/envs/safety_gymnasium_env.py
  omnisafe/envs/safety_gymnasium_modelbased.py
  omnisafe/envs/wrapper.py
  omnisafe/utils/distributed.py
  omnisafe/utils/model.py
  omnisafe/utils/schedule.py
  tests/simple_env.py
Labels: enhancement, environment

#269 fix(envs): Enable auto reset for MuJoCo envs
  omnisafe/envs/mujoco_env.py
Labels: bug, environment, algorithm

#272 docs: pin dependency
  docs/requirements.txt
Labels: bug, documentation, dependency
